# Assignment 9.1

> Replace all TODOs with your code. Do not change any other code.

In [1]:
# Do not edit this cell

import numpy as np
import pandas as pd
import random

## Numpy

### Task 1

Create a 1D numpy array with elements [1, 2, 3, 4, 5]. Do it in two different ways.


In [2]:
res = np.arange(1,6)

print(res)

[1 2 3 4 5]


In [3]:
res2 = np.array([1,2,3,4,5])

print(res2)

[1 2 3 4 5]


### Task 2

Create a 2D numpy array with shape (3, 5) filled with random integers between 1 and 100.

In [4]:
res3 = np.random.randint(low=1, high=100, size =(3, 5))


print(res3)

[[71 69 13 69 55]
 [52 83 48  8 13]
 [75 95 63 85 25]]


### Task 3

Print the first row of array `res3`.

In [5]:
print(res3[0])

[71 69 13 69 55]


### Task 4

Access the last column of array `res3`. Assume that the array may be of any 2D shape.

In [6]:
print(res3[:, -1])

[55 13 25]


### Task 5

Find the min, max, and sum of elements of the second column of array `res3`.

In [7]:
# Min
res_min = res3[:, 1].min()

print('min =', res_min)

min = 69


In [8]:
# Max
res_max = res3[:, 1].max()

print('max =', res_max)

max = 95


In [9]:
# Sum
res_sum = sum(res3[:, 1])

print('sum =', res_sum)

sum = 247


### Task 6

Tabulate the function

$$f(x) = e^{2x}$$

on interval `[0, 1]` with step 0.1.

By "tabulate" we mean that we want to have a table (1D array), where on the first position we will have the function value for 0, on the second position 0.1, and so on.

In [10]:
x = np.arange(0, 1.1, 0.1)
f_x = np.exp(2*x)

print(f_x)


[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183
 3.32011692 4.05519997 4.95303242 6.04964746 7.3890561 ]


## Pandas

We will be working on the classic dataset for beginner data scientists: Titanic passengers.

### Task 7

Load the dataset from the following URL: https://web.stanford.edu/class/cs102/datasets/Titanic.csv

In [11]:
df = pd.read_csv('https://web.stanford.edu/class/cs102/datasets/Titanic.csv')

### Task 8

Let's see the series/columns present in the data frame.

Also, let's inspect the first ten rows of data.

In [12]:
print(df)

          last                                       first gender   age  \
0       Braund                             Mr. Owen Harris      M  22.0   
1      Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0   
2    Heikkinen                                  Miss Laina      F  26.0   
3     Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0   
4        Allen                           Mr. William Henry      M  35.0   
..         ...                                         ...    ...   ...   
886   Montvila                                 Rev. Juozas      M  27.0   
887     Graham                         Miss Margaret Edith      F  19.0   
888   Johnston               Miss Catherine Helen "Carrie"      F   NaN   
889       Behr                             Mr. Karl Howell      M  26.0   
890     Dooley                                 Mr. Patrick      M  32.0   

     class     fare     embarked survived  
0        3   7.2500  Southampton       no  
1        1 

In [13]:
print(df[:10])

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   
5      Moran                                   Mr. James      M   NaN      3   
6   McCarthy                               Mr. Timothy J      M  54.0      1   
7    Palsson                        Master Gosta Leonard      M   2.0      3   
8    Johnson    Mrs. Oscar W (Elisabeth Vilhelmina Berg)      F  27.0      3   
9     Nasser                 Mrs. Nicholas (Adele Achem)      F  14.0      2   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  So

### Task 9

Add a new column - full name - it should be a concat of the first and last name.

In [52]:
df['full name!'] = df['first'] + ' ' + df['last']

print(df)

# print(df['first'] +' '+df['last']  , 'SSSS')

          last                                       first gender   age  \
0       Braund                             Mr. Owen Harris      M  22.0   
1      Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0   
2    Heikkinen                                  Miss Laina      F  26.0   
3     Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0   
4        Allen                           Mr. William Henry      M  35.0   
..         ...                                         ...    ...   ...   
886   Montvila                                 Rev. Juozas      M  27.0   
887     Graham                         Miss Margaret Edith      F  19.0   
888   Johnston               Miss Catherine Helen "Carrie"      F   NaN   
889       Behr                             Mr. Karl Howell      M  26.0   
890     Dooley                                 Mr. Patrick      M  32.0   

     class     fare     embarked survived  \
0        3   7.2500  Southampton       no   
1        

### Task 10

Remove the two original columns - last, first.

In [54]:
df.drop(columns=['first', 'last', 'full name'], axis=1)

gender   age  class     fare     embarked survived  \
0        M  22.0      3   7.2500  Southampton       no   
1        F  38.0      1  71.2833    Cherbourg      yes   
2        F  26.0      3   7.9250  Southampton      yes   
3        F  35.0      1  53.1000  Southampton      yes   
4        M  35.0      3   8.0500  Southampton       no   
..     ...   ...    ...      ...          ...      ...   
886      M  27.0      2  13.0000  Southampton       no   
887      F  19.0      1  30.0000  Southampton      yes   
888      F   NaN      3  23.4500  Southampton       no   
889      M  26.0      1  30.0000    Cherbourg      yes   
890      M  32.0      3   7.7500   Queenstown       no   

                                            full name!  
0                               Mr. Owen Harris Braund  
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  
2                                 Miss Laina Heikkinen  
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  
4                              Mr. William Henry Allen  
..                                                 ...  
886                               Rev. Juozas Montvila  
887                         Miss Margaret Edith Graham  
888             Miss Catherine Helen "Carrie" Johnston  
889                               Mr. Karl Howell Behr  
890                                 Mr. Patrick Dooley  

[891 rows x 7 columns]

### Task 11

Calculate the total number of survivors in the dataset.

In [66]:
df[df == 'yes'] = 1
df[df == 'no'] = None
df['survived'].sum(axis=0)


342