# Intro to scientific Python

## Numpy

> The contents are adapted from Stanford course CS231 - [source](https://cs231n.github.io/python-numpy-tutorial/).


Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.


To use Numpy, we first need to install it and then import the `numpy` package:

`pip install numpy`

In [1]:
import numpy as np

### Why numpy?
[NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html):
> NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use



In [32]:
from timeit import timeit

setup = '''
import numpy as np

li = list(range(1000))
ar = np.arange(1000)
'''

s1 = '''li2 = [x ** 2 for x in li]'''
s2 = '''ar2 = ar ** 2'''

print(f'Time for Python list: {timeit(s1, setup, number=10000)} s')
print(f'Time for numpy array: {timeit(s2, setup, number=10000)} s')

Time for Python list: 1.5180828339998698 s
Time for numpy array: 0.005283500000132335 s


### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> 1 2 3
[5 2 3]


In [34]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [35]:
print(b.shape)
print(b[1, 2])

(2, 3)
6


Here's how we determine the shape of array:

![Shapes example](https://www.oreilly.com/api/v2/epubs/9781491922927/files/assets/elsp_0105.png)

### Other init methods

Numpy also provides many functions to create arrays.

In [36]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [37]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [38]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [39]:
e = np.arange(4)     # similar to bult-in range()
print(e)

[0 1 2 3]


In [40]:
f = np.random.random((2,2)) # Create an array filled with random values
print(f)

[[0.30126611 0.983501  ]
 [0.35377195 0.26552811]]


### Array slicing

Numpy offers several ways to index arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [41]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12],
])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [42]:
print(a)
b[0, 0] = 77
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


We can change several elements at a time.

In [46]:
print(a)
a[0, :3] = [54, 53, 52]
print(a)

[[54 53 52  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[54 53 52  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [47]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

# An example of integer array indexing.
# The returned array will have shape (3,) and
xs = [0, 1, 2]
ys = [0, 1, 0]

print(a[xs, ys])
# same as
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]
[1 4 5]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [48]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4],
    [5, 1],
])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True False]]


In [49]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5]
[3 4 5]


### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [51]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int16)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int16


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate **elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module:

![elementwise operarions](https://datascienceparichay.com/wp-content/uploads/2021/07/elementwise-multiplication-of-numpy-arrays.png.webp)

In [52]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [53]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [54]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [55]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


![numpy power](https://cdn-coiao.nitrocdn.com/CYHudqJZsSxQpAPzLkHFOkuzFKDpEHGF/assets/static/optimized/rev-85bf93c/wp-content/uploads/2019/07/apply-exponent-to-array-of-bases-np-power.png)

In [57]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


print(np.power(x, 2))
# same as
print(x ** 2)

print(x * 2)

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 1.  4.]
 [ 9. 16.]]
[[ 1.  4.]
 [ 9. 16.]]
[[2. 4.]
 [6. 8.]]


Note that `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:
![numpy dot](https://i.ytimg.com/vi/ZUeSxQ67wD8/maxresdefault.jpg)

In [58]:
v = np.array([10, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

230
230


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

## Additional materials

[NumPy - Learn](https://numpy.org/learn/)

[More than 15 jupyter notebooks to learn Numpy](https://www.kaggle.com/getting-started/115421)
